baseline: false
bf16: false
bnb_4bit_compute_dtype: float16
bnb_4bit_quant_type: nf4
cache_dir: model/
ckpt_path: results/
fp16: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
group_by_length: false
learning_rate: 0.0002
load_dir: null
logging_steps: 10
lora_alpha: 16
lora_dropout: 0.1
lora_r: 64
lr_scheduler_type: constant
max_grad_norm: 0.3
max_seq_length: 512
max_steps: 5000
model_name: model/llama2/7B-chat
num_train_epochs: 1
optim: paged_adamw_32bit
packing: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
save_steps: 10
save_total_limit: 100
use_4bit: true
use_nested_quant: false
warmup_ratio: 0.03
weight_decay: 0.001
with_self_instruct: true
